# Generated by Django 3.1.7 on 2021-04-10 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='tag_like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='tag_save_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
