# Generated by Django 3.1.7 on 2021-03-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210322_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
