# Generated by Django 3.1.7 on 2021-07-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.information'),
        ),
        migrations.AddField(
            model_name='contactcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comment'),
        ),
        migrations.AddField(
            model_name='contactcomment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
