# Generated by Django 3.1.7 on 2021-07-14 02:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contact', '0003_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='해시태그를 입력해주세요', through='contact.TaggedContact', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
