# Generated by Django 3.1.7 on 2021-04-10 16:19

from django.db import migrations, models
import django_mysql.models
import reference.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=reference.utils.uuid_name_upload_to)),
                ('desc', models.TextField()),
                ('image_url', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=60000, size=None)),
                ('tag_str', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
