# Generated by Django 3.1.7 on 2021-04-10 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        ('core', '0002_auto_20210411_0119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='reference_like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='reference_save_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='references', to='core.Tag'),
        ),
    ]
