# Generated by Django 3.1.7 on 2021-03-23 12:41

from django.db import migrations, models
import django.db.models.deletion
import portfolio.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210322_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio.utils.uuid_name_upload_to, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='portfolio.portfolio')),
            ],
        ),
    ]
